/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Quadratic;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author rafael_1
 */
public class VentanaQuadratic extends javax.swing.JFrame {
    String cadena_salida_desarrollo=""; 
    /**
     * Creates new form VentanaQuadratic
     */
    public VentanaQuadratic() {
        initComponents();
        limpiar.setBorder(null);
        calcular.setBorder(null);
        salir.setBorder(null);
        panel1.setBorder(null);
        valor_b.setBorder(null);
        valor_n.setBorder(null);
        valor_x.setBorder(null);
        factor1.setBorder(null);
        factor2.setBorder(null); 
        detalles.setBorder(null);
        salida_final_multiplicando.setBorder(null);
        
        //panel2.setBorder(null);
        //panel3.setBorder(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        calcular = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valor_x = new javax.swing.JTextField();
        valor_b = new javax.swing.JTextField();
        valor_n = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        factor1 = new javax.swing.JTextField();
        factor2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        salida_final_multiplicando = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        detalles = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUADRATIC SIEVE");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 215, 96));
        jLabel1.setText("ALGORITMO QUADRATIC SIEVE");

        panel1.setBackground(new java.awt.Color(40, 40, 40));

        calcular.setBackground(new java.awt.Color(40, 40, 40));
        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Calculator_32 (2).png"))); // NOI18N
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpiar.setBackground(new java.awt.Color(40, 40, 40));
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rubber_32 (2).png"))); // NOI18N
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 175, 178));
        jLabel2.setText("INGRESE X:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(174, 175, 178));
        jLabel3.setText("INGRESE B:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(174, 175, 178));
        jLabel4.setText("INGRESE N:");

        valor_x.setBackground(new java.awt.Color(40, 40, 40));
        valor_x.setForeground(new java.awt.Color(30, 215, 96));
        valor_x.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_x.setCaretColor(new java.awt.Color(30, 215, 96));
        valor_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_xActionPerformed(evt);
            }
        });

        valor_b.setBackground(new java.awt.Color(40, 40, 40));
        valor_b.setForeground(new java.awt.Color(30, 215, 96));
        valor_b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_b.setCaretColor(new java.awt.Color(30, 215, 96));

        valor_n.setBackground(new java.awt.Color(40, 40, 40));
        valor_n.setForeground(new java.awt.Color(30, 215, 96));
        valor_n.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_n.setCaretColor(new java.awt.Color(30, 215, 96));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(174, 175, 178));
        jLabel6.setText("FACTOR 1:");

        factor1.setEditable(false);
        factor1.setBackground(new java.awt.Color(40, 40, 40));
        factor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        factor1.setForeground(new java.awt.Color(30, 215, 96));
        factor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        factor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factor1ActionPerformed(evt);
            }
        });

        factor2.setEditable(false);
        factor2.setBackground(new java.awt.Color(40, 40, 40));
        factor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        factor2.setForeground(new java.awt.Color(30, 215, 96));
        factor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(174, 175, 178));
        jLabel7.setText("FACTOR 2:");

        salida_final_multiplicando.setEditable(false);
        salida_final_multiplicando.setBackground(new java.awt.Color(40, 40, 40));
        salida_final_multiplicando.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salida_final_multiplicando.setForeground(new java.awt.Color(30, 215, 96));
        salida_final_multiplicando.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salida_final_multiplicando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_final_multiplicandoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(174, 175, 178));
        jLabel8.setText("RESULTADO :");

        detalles.setBackground(new java.awt.Color(40, 40, 40));
        detalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Binoculars_32.png"))); // NOI18N
        detalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor_b, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valor_x, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valor_n))
                .addGap(45, 45, 45)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalles, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(factor1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(salida_final_multiplicando)
                    .addComponent(factor2))
                .addGap(41, 41, 41))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(valor_n, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factor1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_x, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(factor2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(detalles, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(salida_final_multiplicando, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        salir.setBackground(new java.awt.Color(24, 24, 24));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("SALIR");
        salir.setBorderPainted(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_xActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
         
        String salida_desarrollo="";  
        
        Quadratic quadratic= new Quadratic(Integer.parseInt(valor_b.getText()),Integer.parseInt(valor_n.getText()),Integer.parseInt(valor_x.getText()));
        quadratic.CalcularQuadratic();
        salida_desarrollo=salida_desarrollo+("FACTORES BASE: \n");
        for(int g=0;g<quadratic.factores_base.size();g++)
        {
            salida_desarrollo=salida_desarrollo+("["+quadratic.factores_base.get(g)+"]   ");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        }
        salida_desarrollo=salida_desarrollo+("\n\n");
        //hola.setText(salida_desarrollo);
       // ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("NUMERO DE FACTORES BASE: "+quadratic.t+"\n\n");
        //hola.setText(salida_desarrollo);
        //vayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("M: "+quadratic.m+"\n\n");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("\tX+M \t\t B \t\t FACTORES\n");
        //hola.setText(salida_desarrollo);
       // ayudita.add(hola);
        for(int p=0;p<quadratic.posqsuave.size();p++)
        {
            salida_desarrollo=salida_desarrollo+("\t"+quadratic.posqsuave.get(p)+"\t\t"+quadratic.aux_B.get(p)+"\t\t"+quadratic.qsuave.get(p)+"\n");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        }
        //MOSTRANDO MATRIZ MOD 2
        salida_desarrollo=salida_desarrollo+("\n\n");
        //hola.setText(salida_desarrollo);
       // ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("MATRIZ QSUAVE MOD2\n");
       // hola.setText(salida_desarrollo);
      //  ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("\t X+M\t b\t\t\t\t FACTORES BASE\t\t\t q(x) suave\n");
      //  hola.setText(salida_desarrollo);
      //  ayudita.add(hola);
        for(int f=0;f<quadratic.posqsuave.size();f++)
        {
            salida_desarrollo=salida_desarrollo+("\t"+quadratic.posqsuave.get(f)+"\t"+quadratic.aux_B.get(f)+"\t\t");
      //  hola.setText(salida_desarrollo);
     //   ayudita.add(hola);
            for(int p=0;p<quadratic.t;p++)
            {
                salida_desarrollo=salida_desarrollo+(quadratic.qsuaveM2[f][p]+"\t");
       // hola.setText(salida_desarrollo);
        //ayudita.add(hola);
            }
            salida_desarrollo=salida_desarrollo+(""+quadratic.qsuave.get(f)+"\n");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        }
        salida_desarrollo=salida_desarrollo+("\n");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("COMBINACIONES DE FILAS A SUMAR INTENTADAS: {");
//        hola.setText(salida_desarrollo);
//        ayudita.add(hola);
        for(int k=0;k<quadratic.PosicionFinalQsuave.size();k++)
        {
            if (k==(quadratic.PosicionFinalQsuave.size()-1)) {
                salida_desarrollo=salida_desarrollo+(""+(quadratic.PosicionFinalQsuave.get(k)+1));
//        hola.setText(salida_desarrollo);
//        ayudita.add(hola);
            }
            else
            {
                salida_desarrollo=salida_desarrollo+(""+(quadratic.PosicionFinalQsuave.get(k)+1)+",");
//        hola.setText(salida_desarrollo);
        //ayudita.add(hola);
            }
        }
        salida_desarrollo=salida_desarrollo+("}\n\n");
        ////hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("X="+quadratic.X+"\n");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("Y="+quadratic.Y+"\n");
        //hola.setText(salida_desarrollo);
        //ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("MCD("+(quadratic.X-quadratic.Y)+","+quadratic.n+")= "+quadratic.f2+"\n");
//        hola.setText(salida_desarrollo);
//        ayudita.add(hola);
        salida_desarrollo=salida_desarrollo+("MCD("+(quadratic.X+quadratic.Y)+","+quadratic.n+")= "+quadratic.f1+"\n");
  //      hola.setText(salida_desarrollo);
  //      ayudita.add(hola);
        factor1.setText(""+quadratic.f1);
        factor2.setText(""+quadratic.f2);
        salida_final_multiplicando.setText(String.valueOf(quadratic.f1*quadratic.f2));
        cadena_salida_desarrollo=salida_desarrollo;
    }//GEN-LAST:event_calcularActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        valor_n.setText("");
        valor_b.setText("");
        valor_x.setText("");
        //desarrollo.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void factor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factor1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void salida_final_multiplicandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_final_multiplicandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salida_final_multiplicandoActionPerformed

    private void detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesActionPerformed
        // TODO add your handling code here:
        Desarrollo des=new Desarrollo();
        des.algo(cadena_salida_desarrollo);
        des.setVisible(true); 
    }//GEN-LAST:event_detallesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaQuadratic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaQuadratic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaQuadratic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaQuadratic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaQuadratic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JButton detalles;
    private javax.swing.JTextField factor1;
    private javax.swing.JTextField factor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField salida_final_multiplicando;
    private javax.swing.JButton salir;
    private javax.swing.JTextField valor_b;
    private javax.swing.JTextField valor_n;
    private javax.swing.JTextField valor_x;
    // End of variables declaration//GEN-END:variables
}
